[webserver]
port = ":8080"
hostname = "0.0.0.0"

[cache]
type = "file"
basepath = "/tmp/tegola-cache"

[[providers]]
name = "postgis_provider"
type = "postgis"
uri = "postgres://postgres:admin123.@192.168.8.47:5432/TrafficReportDb?sslmode=disable"
srid = 4326
max_connections = 10

  # POI Layer
  [[providers.layers]]
  name = "live_poi"
  geometry_fieldname = "geom"
  id_fieldname = "id"
  sql = """
   SELECT 
      lv.tegola_id as id, 
      lv.id as live_report_id, 
      ct.name as category_name, 
      ct.marker_image_url as marker_url, 
      lv.status,
      lv.created_at,
      lv.number_of_view,
      lv.number_of_confirm,
      lv.number_of_rejection,
      'poi' as feature_type,
      ST_AsBinary(lv.points) AS geom 
    FROM 
      public."live-report-test" lv
    LEFT JOIN public."traffic-category" ct on lv.category_id = ct.id
    WHERE
      lv.points && !BBOX! 
      AND lv.points IS NOT NULL
      AND lv.geom_type = 'POINT'
  """

  # Road Closure Layer
  [[providers.layers]]
  name = "road_closures"
  geometry_fieldname = "geom"
  id_fieldname = "id"
  sql = """
   SELECT 
      lv.tegola_id as id, 
      lv.id as live_report_id, 
      ct.name as category_name, 
      '' as marker_url, 
      lv.status,
      lv.created_at,
      lv.number_of_view,
      lv.number_of_confirm,
      lv.number_of_rejection,
      'road_closure' as feature_type,
      ST_AsBinary(lv.lines) AS geom 
    FROM 
      public."live-report-test" lv
    LEFT JOIN public."traffic-category" ct on lv.category_id = ct.id
    WHERE
      lv.lines && !BBOX! 
      AND lv.lines IS NOT NULL
      AND lv.geom_type = 'ROAD_CLOSED'
   
   UNION ALL
   
    SELECT 
      lv.tegola_id as id, 
      lv.id as live_report_id, 
      ct.name as category_name, 
      ct.marker_image_url as marker_url, 
      lv.status,
      lv.created_at,
      lv.number_of_view,
      lv.number_of_confirm,
      lv.number_of_rejection,
      'entry_point' as feature_type,
      ST_AsBinary(lv.points) AS geom 
    FROM 
      public."live-report-test" lv
    LEFT JOIN public."traffic-category" ct on lv.category_id = ct.id
    WHERE
      lv.points && !BBOX! 
      AND lv.points IS NOT NULL
      AND lv.geom_type = 'ROAD_CLOSED'  
     
  """
    
# Live reports map with separate layers
[[maps]]
name = "livereports"
attribution = "© Live Reports"
bounds = [-180.0, -85.0511, 180.0, 85.0511]
center = [106.675327, 10.7590847, 14.0]  # Ho Chi Minh City

  [[maps.layers]]
  name = "live_poi"
  provider_layer = "postgis_provider.live_poi"
  min_zoom = 10
  max_zoom = 22
  
    [maps.layers.default_tags]
    class = "live_poi"

  [[maps.layers]]
  name = "road_closures"
  provider_layer = "postgis_provider.road_closures"
  min_zoom = 10
  max_zoom = 22
  
    [maps.layers.default_tags]
    class = "road_closures"